<?php

namespace DL2015\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChallengeRepository extends EntityRepository {

    public function findByCurrentDate() {
        date_default_timezone_set('Europe/Paris');
        $date = date('Y/m/d', time());
        $qb = $this->createQueryBuilder('c');
        $qb->where('c.datdebut < :date')
                ->setParameter('date', new \Datetime(date($date)))
                ->andWhere('c.datfin > :date')
                ->setParameter('date', new \Datetime(date($date)));
        return $qb->getQuery()->getResult();
    }

}
