<?php

namespace DL2015\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LicencieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicencieRepository extends EntityRepository
{
}
