<?php

namespace DL2015\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipeRepository extends EntityRepository {

    public function getPart($numvoil, $idregate) {



        $qb = $this->createQueryBuilder('p');
        $qb->where('p.numvoil = :numvoil')
            ->setParameter('numvoil', $numvoil)
            ->andWhere('p.numreg = :idregate')
            ->setParameter('idregate', $idregate);
        

        return $qb->getQuery()->getResult();
    }

}
