<?php

namespace DL2015\IndexBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegateRepository extends EntityRepository
{
public function getRegate(){
    date_default_timezone_set('Europe/Paris');
        $date = date('Y/m/d', time());
return $this
->createQueryBuilder('r')
->join('r.cdochal', 'chal')
->addSelect('chal')
->where('chal.datdebut < :date')
->setParameter('date', new \Datetime(date($date)))
->andWhere('chal.datfin > :date')
->setParameter('date', new \Datetime(date($date)))
->andWhere('r.datreg > :date')
->setParameter('date', new \Datetime(date($date)));

;
}
}
