dl2015_index_homepage:
    path:     /index
    defaults: { _controller: DL2015IndexBundle:Log:index }

dl2015_regate:
    path:     /register/regate
    defaults: { _controller: DL2015IndexBundle:Register:regate }

dl2015_voilier:
    path:     /register/voilier
    defaults: { _controller: DL2015IndexBundle:Register:voilier }
    
dl2015_logout:
    path:     /logout
    defaults: { _controller: DL2015IndexBundle:Log:logout }
    
dl2015_nolog:
     path:     /error/log
     defaults: { _controller: DL2015IndexBundle:Register:noLog }
     
dl2015_voilier_error:
    path:     /error/voilier
    defaults: { _controller: DL2015IndexBundle:Register:noVoilier }
    
dl2015_proprio:
    path:     /register/proprietaire
    defaults: { _controller: DL2015IndexBundle:Register:proprietaire }
    
dl2015_equip1:
     path:     /register/equipage/1
     defaults: { _controller: DL2015IndexBundle:Register:equip1 }
     
dl2015_equip2:
     path:     /register/equipage/2
     defaults: { _controller: DL2015IndexBundle:Register:equip2 }
    