dl2015_index_homepage:
    path:     /index
    defaults: { _controller: DL2015IndexBundle:Log:index }

dl2015_register:
    path:     /register
    defaults: { _controller: DL2015IndexBundle:Register:register }
    
dl2015_logout:
    path:     /logout
    defaults: { _controller: DL2015IndexBundle:Log:logout }
    
dl2015_nolog:
     path:     /error
     defaults: { _controller: DL2015IndexBundle:Register:noLog }
    