dl2015_index_homepage:
    path:     /index
    defaults: { _controller: DL2015IndexBundle:Default:index }

dl2015_register:
    path:     /register
    defaults: { _controller: DL2015IndexBundle:Default:register }
    
dl2015_logout:
    path:     /logout
    defaults: { _controller: DL2015IndexBundle:Default:logout }